# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files




-   repo: local
    hooks:

    -   id: isort
        name: isort
        entry: isort ./src
        language: python
        types: [text]
        pass_filenames: false

    -   id: black
        name: black
        entry: black ./src --line-length 120
        language: python
        types: [text]
        pass_filenames: false

    -   id: pylama
        name: pylama
        entry: pylama src --async --linters eradicate,mccabe,mypy,pycodestyle,pyflakes,pylint,isort
        language: python
        types: [text]
        pass_filenames: false
