# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: [commit-msg, pre-merge-commit, pre-commit, pre-push]

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          ["@commitlint/config-conventional", "@commitlint/format"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        # FIXME: Doesn't format toml and gitignore?
        # FIXME: Doesn't warn when failed to format (eg, broken syntax)
        types_or: [yaml, markdown]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.269"
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [tokenize-rt==3.2.0]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: requirements-txt-fixer
      - id: check-merge-conflict
        name: "check for merge conflict strings"
      - id: no-commit-to-branch
        name: "don't commit directly to main"
